"""rename razorpay field to stripe payment intent id

Revision ID: 5d67562b5cfb
Revises: 
Create Date: 2026-08-06 19:15:31.546360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d67562b5cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('razorpay_payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_payment_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('stripe_payment_intent_id')

    # ### end Alembic commands ###
